source 'https://rubygems.org'
ruby '2.6.3'

gem 'sinatra',            '2.2.3'
gem 'data_mapper',        '1.2.0'
gem 'dm-postgres-adapter'
gem 'json',               '1.8.6'
gem 'shotgun',            '0.9.2'
gem 'slim',               '3.0.8'
gem 'thin',               '1.7.0'
gem 'sinatra-formhelpers-ng'
gem 'dotenv'
gem 'httparty'